events {}

http {
    upstream auth_upstream {
        server auth:8000;
    }
    upstream api_upstream {
        server api:8000;
    }

    server {
        listen 80;

        location ~ ^/(register|login|auth/docs|auth/openapi.json) {
            proxy_pass http://auth_upstream;
        }

        location ~ ^/(logs|api/docs|api/openapi.json) {
            proxy_pass http://api_upstream;
        }
    }
}